name: README.md

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

env:
  BOT_USER: "martcus-bot"
  EMAIL_USER: "<>"

jobs:
  readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Update README
      run: |
        node .github/scripts/readme.js
    - name: Show README
      run: |
        cat README.md
    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "$BOT_MAIL"
        git config --global user.name "$BOT_USER"
        git add -A
        git commit -m "Update quote of the day " || exit 0
        git push
